In [57]:
print("using tensorflow")

import tensorflow as tf
tf.__version__

node = tf.constant(9)
node2 = tf.constant(8)

print(node+node2)


using tensorflow
tf.Tensor(17, shape=(), dtype=int32)


In [58]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


In [59]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [60]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.29053736,  0.5270382 , -0.4178799 , -0.41808432,  0.1316142 ,
        -0.12616193, -0.21187076,  0.08287759,  0.42886344,  0.3237054 ]],
      dtype=float32)

In [61]:
tf.nn.softmax(predictions).numpy()

array([[0.11956768, 0.15146938, 0.05887787, 0.05886583, 0.10199863,
        0.07882129, 0.07234703, 0.09714676, 0.13730554, 0.12360001]],
      dtype=float32)

In [62]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [63]:
loss_fn(y_train[:1], predictions).numpy()

probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [64]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [65]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
  20/1875 [..............................] - ETA: 10s - loss: 1.8537 - accuracy: 0.4641

2022-10-25 01:06:00.220550: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1875/1875 [==============================] - 10s 5ms/step - loss: 0.2891 - accuracy: 0.9167
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1390 - accuracy: 0.9591
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1019 - accuracy: 0.9693
Epoch 4/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0814 - accuracy: 0.9743
Epoch 5/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0687 - accuracy: 0.9784


In [66]:
model.evaluate(x_test,  y_test, verbose=2)


2022-10-25 01:06:50.735814: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


313/313 - 1s - loss: 0.0795 - accuracy: 0.9771 - 1s/epoch - 4ms/step


[0.0794517770409584, 0.9771000742912292]

In [67]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [68]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.8741740e-07, 4.9210716e-09, 4.9368660e-05, 1.7023486e-03,
        6.4361783e-10, 8.2903362e-06, 7.0259727e-13, 9.9820673e-01,
        2.5660945e-06, 3.0539162e-05],
       [3.5363657e-06, 2.2164757e-05, 9.9974197e-01, 1.9885543e-04,
        3.9352158e-14, 2.0482330e-06, 1.1316131e-05, 9.4683116e-13,
        2.0079931e-05, 9.5477814e-13],
       [7.3955925e-07, 9.9861282e-01, 4.5059533e-05, 4.3031716e-05,
        1.0656475e-04, 4.4342338e-05, 9.8077013e-05, 3.7154838e-04,
        6.7032059e-04, 7.4778941e-06],
       [9.9964046e-01, 1.8214295e-12, 4.5377841e-05, 4.5615259e-08,
        7.9226822e-07, 4.8288421e-06, 3.0171941e-04, 5.9667868e-06,
        3.4686789e-08, 6.7468034e-07],
       [4.1827107e-06, 7.2829914e-10, 7.6881315e-06, 3.2990272e-08,
        9.9227732e-01, 2.9427940e-07, 1.6557951e-07, 5.9365160e-05,
        1.0178308e-06, 7.6499972e-03]], dtype=float32)>